# Generated by Django 4.1.7 on 2023-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customerName", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=10, null=True)),
                ("numberPlate", models.CharField(max_length=10)),
                ("services", models.JSONField(default=dict)),
            ],
        ),
    ]
